language: node_js
node_js:
- 10.15.1
env:
  matrix:
  - VSCODE_VERSION="1.33.1" MAJOR_VERSION="1" VERSION="$MAJOR_VERSION.$TRAVIS_BUILD_NUMBER-vsc$VSCODE_VERSION"
  global:
  - secure: nKAdbbM3rBT0S0wTgtbIgWnlE+gJxsj1B37juaik218ZywA6jskN0rwhH0mQANg1Zw8NsEFaP8Pw6gLLSk6YFZhjx4pCh0yTheMx7p7MUim93b9egKgSDZPl5wetMcVWPt3KFgWDBwdwAdwXsJEtF/aMVANEihN6Wxg/i5DxuEDKEuOQ8DDXsOaaMXX984UM+86dRp+W9PbFac6SsXteEzXyLWMTKytsD3JR4fP6ccJWRnrDqKmBEIjCmphYA/hfmf/goFsHAknSc1S7J0NxMIFuJt7adbn7dRSKUmsJj6NK5B7+0OSBEJGrRSemwoqYuKeuSIe5wWTVzNuGLIMukvrnjxrLqcxFsg7S1cTzerJexSrSb6nftlPokbckuyTFprXNKpaQNcQOCSHAPM/k1usmWwH1ewcLSEcKEN6vduisHHvCTelioWTczAe0XNRELMGHdJ0am2SSMA7/hTbMbmAfZ5iIgDpNBDRaPcqqsIe4kK7FTuEeli7EX0iB7Z0M4o0q//0hElkxx/2o5oTgx/saMXOp65lvfdNqcn2UFoUOb2OxN3nqniCSOcMfyxBo6bqUevdYjtMVqgOexAED7EGeBw4JdaPqxk1hhTZdoaQfdktVDifizT0duUb6HqU0i/PmFCoAMa+qKNm8BspbOvqhv6y0HZTPYVeVDhgDccM=
matrix:
  include:
  - os: linux
    dist: trusty
  - os: osx
before_install:
- if [[ "$GCP_CREDENTIALS" != "" ]]; then
  echo "$GCP_CREDENTIALS" > test/.coder-gcp-credentials.json; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  sudo apt-get install -y libxkbfile-dev libsecret-1-dev; fi
- npm install -g yarn@1.12.3
script:
- scripts/build.sh
before_deploy:
- echo "$VERSION" "$TRAVIS_COMMIT"
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- git tag "$VERSION" "$TRAVIS_COMMIT"
- yarn task package "$VERSION"
deploy:
  provider: releases
  file_glob: true
  draft: true
  tag_name: "$VERSION"
  target_commitish: "$TRAVIS_COMMIT"
  name: "$VERSION"
  skip_cleanup: true
  api_key:
    secure: YL/x24KjYjgYXPcJWk3FV7FGxI79Mh6gBECQEcdlf3fkLEoKFVgzHBoUNWrFPzyR4tgLyWNAgcpD9Lkme1TRWTom7UPjXcwMNyLcLa+uec7ciSAnYD9ntLTpiCuPDD1u0LtRGclSi/EHQ+F8YVq+HZJpXTsJeAmOmihma3GVbGKSZr+BRum+0YZSG4w+o4TOlYzw/4bLWS52MogZcwpjd+hemBbgXLuGU2ziKv2vEKCZFbEeA16II4x1WLI4mutDdCeh7+3aLzGLwDa49NxtsVYNjyNFF75JhCTCNA55e2YMiLz9Uq69IXe/mi5F7xUaFfhIqqLNyKBnKeEOzu3dYnc+8n3LjnQ+00PmkF05nx9kBn3UfV1kwQGh6QbyDmTtBP07rtUMyI14aeQqHjxsaVRdMnwj9Q2DjXRr8UDqESZF0rmK3pHCXS2fBhIzLE8tLVW5Heiba2pQRFMHMZW+KBE97FzcFh7is90Ait3T8enfcd/PWFPYoBejDAdjwxwOkezh5N5ZkYquEfDYuWrFi6zRFCktsruaAcA+xGtTf9oilBBzUqu8Ie+YFWH5me83xakcblJWdaW/D2rLJAJH3m6LFm8lBqyUgDX5t/etob6CpDuYHu5D1J3XINOj/+aLAcadq6qlh70PMZS3zYffUu3JlzaD2amlSHIT8b5YXFc=
  file:
  - release/*.tar.gz
  - release/*.zip
  on:
    repo: codercom/code-server
    branch: master
cache:
  yarn: true
  timeout: 1000
  directories:
  - ".cache"
